const ACTION_TYPES = {
  //TODO
  GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
  GET_TASKS_SUCCESS: ' GET_TASKS_SUCCESS',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',
  GET_TASKS_ACTION: 'GET_TASKS_ACTION',

  CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',
  CREATE_TASK_ACTION: 'CREATE_TASK_ACTION',

  UPDATE_TASK_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_TASK_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',
  UPDATE_TASK_ACTION: 'UPDATE_TASK_ACTION',

  DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',
  DELETE_TASK_ACTION: 'DELETE_TASK_ACTION',

  //THEME
  CHANGE_THEME_REQUEST: 'CHANGE_THEME_REQUEST',
  CHANGE_THEME_SUCCESS: 'CHANGE_THEME_SUCCESS',
  CHANGE_THEME_ERROR: 'CHANGE_THEME_ERROR',
  CHANGE_THEME_ACTION: 'CHANGE_THEME_ACTION',
};

export default ACTION_TYPES;
