const ACTION_TYPES = {
  //TODO
  CREATE_TASK_ACTION: 'CREATE_TASK_ACTION',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',
  UPDATE_TASK_ACTION: 'UPDATE_USER_ACTION',
  UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',
  DELETE_TASK_ACTION: 'DELETE_TASK_ACTION',
  DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',
  //THEME
  CHANGE_THEME_ACTION: 'CHANGE_THEME_ACTION',
};

export default ACTION_TYPES;
